const actions = {
   UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
   STORE_QUEUED_TASKS: "STORE_QUEUED_TASKS",
   RESET_TASK_QUEUE: "RESET_TASK_QUEUE",
   STORE_EDITABLE_TASK: "STORE_EDITABLE_TASK",
};

export default actions;
